#ifndef SIM_STATS_INL_HPP
#define SIM_STATS_INL_HPP

#include "../stat_definitions.hpp"

#include <godot_cpp/core/math.hpp>

namespace sim {

// Inline getter functions (hot path) - generated by X-Macro
#define X(name, def, min_val, max_val) \
	inline double get_effective_##name(const UnitState &unit) { \
		double base = (unit.combat.name + unit.stat_additive_##name) * unit.stat_multiplicative_##name; \
		if (min_val != NO_BOUND) { \
			base = Math::max(min_val, base); \
		} \
		if (max_val != NO_BOUND) { \
			base = Math::min(max_val, base); \
		} \
		return base; \
	}
STAT_LIST
#undef X

} // namespace sim

#endif // SIM_STATS_INL_HPP
